default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: exchange_development

test:
  <<: *default
  database: exchange_test

production:
  <<: *default
  database: exchange_production
  username: exchange
  password: <%= ENV["EXCHANGE_DATABASE_PASSWORD"] %>
